<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\SQLite\001_CreateTables.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\SQLite\001_CreateTables.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FLC.PackageManagement\FLC.PackageManagement.csproj" />
  </ItemGroup>
  
  <PropertyGroup>
    <NoWarn>SA1201;$(NoWarn)</NoWarn> <!-- Used version of style cop does not handle primary constructors -->
  </PropertyGroup>
  
</Project>
